import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { fetchTranscript, listLanguages } from "youtube-transcript-plus";

const USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

type TranscriptSegment = {
  text: string;
  offset: number;
  duration?: number;
  lang?: string;
};

type TranscriptResult = TranscriptSegment[] | { segments: TranscriptSegment[]; videoDetails?: Record<string, unknown> };

function asErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}

function formatTimestamp(seconds: number) {
  const totalSeconds = Math.max(0, Math.floor(seconds));
  const h = Math.floor(totalSeconds / 3600);
  const m = Math.floor((totalSeconds % 3600) / 60);
  const s = totalSeconds % 60;

  if (h > 0) return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function extractVideoId(input: string) {
  const trimmed = input.trim();
  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) return trimmed;

  try {
    const url = new URL(trimmed);
    if (url.hostname.includes("youtube.com")) {
      const fromV = url.searchParams.get("v");
      if (fromV && /^[a-zA-Z0-9_-]{11}$/.test(fromV)) return fromV;
      const shorts = url.pathname.match(/\/(?:shorts|embed|live)\/([a-zA-Z0-9_-]{11})/);
      if (shorts) return shorts[1];
    }
    if (url.hostname === "youtu.be" || url.hostname.endsWith(".youtu.be")) {
      const id = url.pathname.split("/").filter(Boolean)[0];
      if (id && /^[a-zA-Z0-9_-]{11}$/.test(id)) return id;
    }
  } catch {
    // Not a URL; fall through to the regex fallback.
  }

  const match = trimmed.match(/(?:v=|youtu\.be\/|shorts\/|embed\/|live\/)([a-zA-Z0-9_-]{11})/);
  return match?.[1] ?? trimmed;
}

async function getTranscript(params: {
  video: string;
  lang?: string;
  timestamps?: boolean;
  listOnly?: boolean;
  includeMetadata?: boolean;
  signal?: AbortSignal;
}) {
  const videoId = extractVideoId(params.video);
  const commonOptions = {
    lang: params.lang || undefined,
    userAgent: USER_AGENT,
    retries: 2,
    retryDelay: 1000,
    signal: params.signal,
  };

  if (params.listOnly) {
    const languages = await listLanguages(videoId, commonOptions);
    const text = languages.length
      ? languages
          .map((language: any) => `- ${language.languageCode}: ${language.languageName}${language.isAutoGenerated ? " (auto-generated)" : ""}`)
          .join("\n")
      : "No transcript languages were reported for this video.";
    return {
      videoId,
      text,
      details: { videoId, languages },
    };
  }

  const result = (await fetchTranscript(videoId, {
    ...commonOptions,
    videoDetails: params.includeMetadata ?? true,
  })) as TranscriptResult;
  const segments = Array.isArray(result) ? result : result.segments;
  const videoDetails = Array.isArray(result) ? undefined : result.videoDetails;

  const text = segments
    .map((entry) => {
      const line = entry.text.replace(/\s+/g, " ").trim();
      if (!params.timestamps) return line;
      return `[${formatTimestamp(entry.offset)}] ${line}`;
    })
    .filter(Boolean)
    .join(params.timestamps ? "\n" : " ");

  return {
    videoId,
    text,
    details: {
      videoId,
      lang: params.lang,
      videoDetails,
      segmentCount: segments.length,
      transcript: segments,
    },
  };
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "youtube_transcript",
    label: "YouTube Transcript",
    description: "Fetch transcripts/captions from YouTube videos for summarization and analysis.",
    promptSnippet: "Fetch timestamped transcripts or available transcript languages for YouTube videos.",
    promptGuidelines: [
      "Use youtube_transcript when the user asks to summarize, analyze, quote, or extract information from a YouTube video transcript.",
    ],
    parameters: Type.Object({
      video: Type.String({ description: "YouTube video ID or URL." }),
      lang: Type.Optional(Type.String({ description: "Optional caption language code, e.g. en, es, fr, pt-BR." })),
      timestamps: Type.Optional(Type.Boolean({ description: "Include [m:ss] timestamps. Defaults to true." })),
      listLanguages: Type.Optional(Type.Boolean({ description: "Only list available transcript languages instead of fetching a transcript." })),
      includeMetadata: Type.Optional(Type.Boolean({ description: "Include YouTube video metadata in tool details. Defaults to true." })),
    }),
    async execute(_toolCallId, params, signal, onUpdate) {
      onUpdate?.({ content: [{ type: "text", text: "Fetching YouTube transcript..." }] });
      try {
        const result = await getTranscript({
          video: params.video,
          lang: params.lang,
          timestamps: params.timestamps ?? true,
          listOnly: params.listLanguages ?? false,
          includeMetadata: params.includeMetadata ?? true,
          signal,
        });
        return {
          content: [{ type: "text", text: result.text }],
          details: result.details,
        };
      } catch (error) {
        return {
          content: [{ type: "text", text: `Error fetching YouTube transcript: ${asErrorMessage(error)}` }],
          details: { error: asErrorMessage(error) },
          isError: true,
        };
      }
    },
  });

  pi.registerCommand("youtube-transcript", {
    description: "Fetch a YouTube transcript. Usage: /youtube-transcript <video-id-or-url> [lang]",
    handler: async (args, ctx) => {
      const [video, lang] = args.trim().split(/\s+/);
      if (!video) {
        ctx.ui.notify("Usage: /youtube-transcript <video-id-or-url> [lang]", "error");
        return;
      }

      try {
        const result = await getTranscript({ video, lang, timestamps: true, includeMetadata: true });
        pi.sendMessage(
          {
            customType: "youtube-transcript",
            content: result.text,
            display: true,
            details: result.details,
          },
          { triggerTurn: false },
        );
        ctx.ui.notify(`Fetched transcript for ${result.videoId}`, "success");
      } catch (error) {
        ctx.ui.notify(`YouTube transcript failed: ${asErrorMessage(error)}`, "error");
      }
    },
  });
}
